package com.example.challenge.domain.model2


data class Hour(
    var condition: Condition,
    var feelslikeC: Double,
    var time: String,
    var tempC: Double,
//    val chanceOfRain: Int,
//    val chanceOfSnow: Int,
//    val cloud: Int,
//    val dewpointC: Double,
//    val dewpointF: Double,
//    val feelslikeF: Double,
//    val gustKph: Double,
//    val gustMph: Double,
//    val heatindexC: Double,
//    val heatindexF: Double,
//    val humidity: Int,
//    val isDay: Int,
//    val precipIn: Double,
//    val precipMm: Double,
//    val pressureIn: Double,
//    val pressureMb: Double,
//    val tempF: Double,
//    val timeEpoch: Int,
//    val uv: Double,
//    val visKm: Double,
//    val visMiles: Double,
//    val willItRain: Int,
//    val willItSnow: Int,
//    val windDegree: Int,
//    val windDir: String,
//    val windKph: Double,
//    val windMph: Double,
//    val windchillC: Double,
//    val windchillF: Double
)